name: bonjour_madame
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  http: ^1.2.2
  intl: ^0.19.0
  meta: ^1.16.0
  rss_dart: ^1.0.10

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
