name: bonjour_madame
description: bonjour_madame is a library allowing to fetch data from the RSS feed of the french erotic website Bonjour Madame.
version: 1.0.0
repository: https://gitlab.projetretro.io/shalien/bonjour_madame
topics:
  - nsfw
  - api
  - rss
  - erotic
  - french

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  http: ^1.2.2
  intl: ^0.19.0
  meta: ^1.16.0
  rss_dart: ^1.0.10

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
